spring.application.name = sistema-biblioteca
spring.datasource.url = jdbc:postgresql://localhost:5432/Biblioteca
spring.datasource.username = postgres
spring.datasource.password = pass123
spring.datasource.driver-class-name = org.postgresql.Driver
debug = true
spring.thymeleaf.cache = false